export const SITE = {
  website: "https://felixoffstage.com/",
  author: "Felix Laundl",
  profile: "https://felixoffstage.com/about",
  desc: "Essays and criticism on European theater.",
  title: "Felix Off Stage",
  ogImage: "og.png",
  lightAndDarkMode: false,
  postPerIndex: 3,
  postPerPage: 10,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: false,
  dir: "ltr",
  lang: "de",
  timezone: "Europe/Vienna",
} as const;
